import './globals.css'
import type { Metadata } from 'next'
import Nav from '@/components/Nav'

import { Poppins } from 'next/font/google'

const poppins = Poppins({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body
        className={`mx-4 md:mx-48 xl:mx-96 bg-zinc-800 text-white ${poppins.className}`}
      >
        <div>
          <Nav />
        </div>
        {children}
      </body>
    </html>
  )
}
